services:
  - type: web
    name:inflation_calculator
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn inflation_calculator.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4